name: FitsinMVP
options:
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.fitsin.mvp
    SWIFT_VERSION: 5.0
targets:
  FitsinMVP:
    type: application
    platform: iOS
    sources:
      - FitsinMVP
    resources:
      - FitsinMVP/Resources
    settings:
      base:
        INFOPLIST_FILE: FitsinMVP/Resources/Info.plist
        PRODUCT_NAME: FitsinMVP
      configs:
        Debug:
          base:
            API_BASE_URL: https://fitsin-mvp.onrender.com
        Release:
          base:
            API_BASE_URL: https://fitsin-mvp.onrender.com
    scheme:
      testTargets: []
